import os
from jinja2 import Environment, FileSystemLoader

# Takes the intermediate AST generated by the java transpiler and uses it to output an SQL file

# code to render a specific model in jinja
def render_model(environment, resources_folder, target_subfolder, model_subfolder, model_name):
    template = environment.get_template(model_subfolder + model_name)
    rendered = template.render()
    with open(resources_folder + target_subfolder + model_name.rsplit('.', 1)[0] + '.sql', 'w') as file:
        file.write(rendered)
        
# creates the jinja environment
target_dialect = 'sparksql'
resources_folder = 'resources/'
jinja_subfolder = 'jinja/'
model_subfolder = 'test_models/'
target_subfolder = "jinja_target/"
env = Environment(loader = FileSystemLoader(resources_folder + jinja_subfolder))
env.add_extension('jinja2.ext.do')
    
# compiles and renders a single, specific model
# render_model(env, resources_folder, target_subfolder, model_subfolder, 'TJCOverallNon_Elective_Inpatient_Encounter.sql')

# for every file inside the models directory, compile it and render it
model_file_names = os.listdir(resources_folder + jinja_subfolder + model_subfolder)
for model in model_file_names:
    render_model(env, resources_folder, target_subfolder, model_subfolder, model)