from jinja2 import Environment, FileSystemLoader

# Takes the intermediate AST generated by the java transpiler and uses it to output an SQL file

target_dialect = 'sparksql'

resources_folder = 'resources/'

jinja_subfolder = 'jinja/'
model_subfolder = 'test_models/'
model_to_translate = 'TJCOverallNon_Elective_Inpatient_Encounter.sql'
target_subfolder = "jinja_target/"

env = Environment(loader = FileSystemLoader(resources_folder + jinja_subfolder))
#env.trim_blocks = True
#env.lstrip_blocks = True
env.add_extension('jinja2.ext.do')
template = env.get_template(model_subfolder + model_to_translate)

rendered = template.render()

with open(resources_folder + target_subfolder + model_to_translate.rsplit('.', 1)[0] + '.sql', 'w') as file:
    file.write(rendered)