from jinja2 import Environment, FileSystemLoader

# Takes the intermediate AST generated by the java transpiler and uses it to output an SQL file

template_dir = 'jinja_output'
cql_to_jinja_source = 'TJCOverall_7.1.000.j2'
env = Environment(loader = FileSystemLoader(template_dir))
env.trim_blocks = True
env.lstrip_blocks = True
env.add_extension('jinja2.ext.do')
template = env.get_template(cql_to_jinja_source)

rendered = template.render()

with open(template_dir + '/' + cql_to_jinja_source.rsplit('.', 1)[0] + '.sql', 'w') as file:
    file.write(rendered)