package gov.va.transpiler.jinja.standards;

/**
 * Used to collect widely-used string fragments and constants, so they can later be provided via system property or program argument.
 */
public class Standards {
    public static final String INDENT = "\t";
    public static final String NEWLINE = "\n";
    public static final String FOLDER_SEPARATOR = "/";
    public static final String SINGLE_VALUE_COLUMN_NAME = "_val";
    public static final String UNSUPPORTED_OPERATOR = "Unsupported";
    public static final String DISABLED_OPERATOR = "Disabled";
    public static final String UNFILTERED_CONTEXT = "Unfiltered";
    public static final String JINJA_FILE_POSTFIX = ".j2";

    private static final String MACRO_FILE_PREFIX = "_macros_";

    private static String targetLanguage;

    /**
     * @return Name of the target language the transpiler should ultimately prepare to convert CQL into.
     */
    public static String getTargetLanguage() {
        return targetLanguage;
    }

    /**
     * @param targetLanguage Name of the target language the transpiler should ultimately prepare to convert CQL into.
     */
    public static void setTargetLanguage(String targetLanguage) {
        Standards.targetLanguage = targetLanguage;
    }

    /**
     * The intermediate AST generated by the transpiler requires a macro file to be translated into the AST of its target language and output as SQL. This function provides the name that file should be called.
     * 
     * @return Name the macro file should be called.
     */
    public static String macroFileName() {
        return MACRO_FILE_PREFIX + getTargetLanguage();
    }
}
